[GOOGLE]
spreadsheet_id = "17D3f_xUvPiKmfzm0_hJEuLk9UL0qrxqiDRAy9O3GfrM"
resume_sheet = "info"
resume_sheet_range = "info!A1:D"
job_sheet = "job"
job_sheet_range = "job!A1:D"
users_sheet = "users"
users_sheet_range = "users!A2:D"
scope = "https://www.googleapis.com/auth/spreadsheets,https://www.googleapis.com/auth/drive"


[DRIVE_FOLDERS]
folder_id = "1yI7Am9HfSa1yeBEa9Uld-ED8yGY0LEMHdsKX0D1-CeFASfOOQShLWy9iK7NtfAHl0t64C_8Q"

[LINKEDIN_AUTH]
org_urn = "urn:li:organization:109573414"
access_token = "AQX8EopOhqQwRZUQew2ULpX1hZqCo9gmfyg7_hxU5QOolLHviBP-6EmPEJqM5K0MxvIDSK4YjxXCHzXvvzgTa8VkXuF_JbjSZ8UZpK8hisJ3mcYXScCEVc9FxZWNV3JhSUjlc9IA2hiEUCfmJrVRgkuOmdLlzbcdM24qhL9rSgwRGLrGHopDhryl9CXT5qkVCaDm-d71KjFVvwhqiPjs-78K-ic_t2byfLbs4norLAVsVFo1pTp-a4LauffXw3eaFz2NRef7p49dRzj0hLMYLEjg-vA2lqbVLZTJV2k3uurFvrACIHflBbqqn88t54ptwLFp8w6M-UZ1hdVYJvGw11vsxOmJng"

[gcp_service_account]
type = "service_account"
project_id = "poised-graph-470206-f8"
private_key_id = "b353270adc7722358d8f71c8abcb28b21b749c3f"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDmqC9+M4z65tUX
bxqhqKu2TO0CyGPdo1MD9EiS3pa6Oz4WhlPRSIHvs6evj+amibqs5rmoSACqWUTa
5gOg69fxAvtgVU7qyyPImA99fGspWR6BLB316BQ5JLqzns9tFENjdhcCDI5vZ6ZV
YwMPTISqTn2muH2mfm7ZL/9Vup/nVVSMjekHU98mhmmTYqleQOcXB5Z6olU3lFg+
jpmrO7l6pnwBjXtIp3J/yECB0d6fgbudUHquTzfqNWug2AmuaVEe5vmSDZitnFoW
UapxlCUJst+m0hPd+1vSI5+Mp6Nr/8P6+kTSOBRmBLJnZY4O4eMemX/slDlLLYWl
DmDmMJxrAgMBAAECggEAIZwBK5z8XnTzOPJuCX9H4gzsfjrP3nRVfN6EEq6PfPxz
7BlPrk+n61MczIal379y7Y3DIMO5IRlX4KOihLjI4uwB0AQuNyU5hhmuLCVMgh5j
xQO2K+ZQyBDTiafK5sSMmzoSWTCWMqKCSK/gOsL2E9DTG0+Hs5J5uXj2djn24eC0
2SKZK0C+yeosuDWXUEKhp6k//6tt6NlUTFcb5JzDl5KoMwc1rbqOF1bMHq9ZFC4L
GLAaqdui9/lsW8tgIziP8ZPiGKYIoqXh0a1msdgIsKOX9XjyXhqLU+HL7bWWjact
nAGBbH3IrJ+uoEj57eDuLEgaQ4EMz+0qkAfEi/iRLQKBgQD3HtY2c6aqi7v3ohIL
ZtuVnUdrm/+pFOFxpfk7XADQ91EmKfIa2Hd9RpWbPAhXcfbafyUABLTs/xsZlhRO
iGvI3TCOMVAV6s+/YUkOR5i6BZYKqH2bl4QUwe7n2XvVP7hReZPp7qWy8egiI2D6
UcRwaQr3wzPODb46mw79apwITQKBgQDu8ehfRqWhlkZR3s8s745WF5Hu7gnThaBO
Qb4R0jwtF2mN7q1pqWbukIbgXuFMpH+SkKxqKdRIRlvsYafJLfyyYZdwQYvJz1Fl
pzVXkejMl2Zc5K1y5iKG5PY4dQDuzgs67Z6PKf1yNfmnOjQZ9I6dh1+F/MKe0Y+p
5/uzUrITlwKBgQC7XrM3KCtXpomH8mfSI1QdNdqAOhD4B7AENr8phdHMn6j00dsT
BcxbvVgUEsmUXAG6m6rXP7pa8/Z9SPDutrta2nNFbRh29co9Jqt420puyWuBe015
2sE35++X9avR/fVoOVGwjtUuQAMtVzvhsHvMa6j4QRaXho4U65rLBLl4BQKBgElL
bRMksZPia8mbRgOrrAaejkYzQFJg7+5xXiNLUOgoAVnnN8xsiUVukeDrWcLPxs4n
kKu0DwjohDP7NKOSdqwlIXXutTl/XaGH6+XjvPxdCKo//zB6hWbJfvmMcm/ORkWa
NAQIRlUtV1pDkU3Q5ZpOty97fBuJfr8IiP3VxQgbAoGAXdFXMgbveHLHtGwY85xA
rhMm10DqLGpStiP6UiZnafRQj5Fww7WT4Yp5ehhE4eH0/aTIAFjTXVYabTa6vT4c
sKPVx1bS6jGsuaqV9Ba8fEYcayqUFTfJ16S1tm6iBmpIh16m2DV8c1hMYwCFO9jX
D5+Ch2zdVhOsFjdDtsh09BI=
-----END PRIVATE KEY-----"""
client_email = "hr-user@poised-graph-470206-f8.iam.gserviceaccount.com"
client_id = "115789839513880579872"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/hr-user%40poised-graph-470206-f8.iam.gserviceaccount.com"
universe_domain = "googleapis.com"